### PR TITLE
Feature: Filtering on Scalar fields

### PR DESCRIPTION
**Pull request by sMteX**
For any information, see PR #49 . This is identical, I messed up with git and I'm not well versed in it to fix my mistakes.

I'm also thinking about updating the Readmes a little, to let users know they can use this feature.

### CODE REVIEW

**Comment by sMteX** [comment]
@macrozone 

Sorry to bother you with a tag, but is this okay? Or did I mess it up with the second commit? Anything else you'd like me to change?

**Comment by macrozone** [comment]
No, its fine!

as long at it has one semantic commit. Without one, it would not create a new release

**Pull request merged**
