### PR TITLE
feat: Add custom input type support for Json field

### PR DESCRIPTION
**Pull request by izziaraffaele**
Solves #35

### CODE REVIEW

**Comment by macrozone** [comment]
woops, did not look at the commits.

We use "semantic-release", where every commit should be prefixed with fix: ... or feat: or similar.

without any fix or feat, no new release gets triggered.

**Comment by macrozone** [comment]
i will now push a commit manually to trigger the release

**Comment by izziaraffaele** [comment]
> woops, did not look at the commits.
> 
> We use "semantic-release", where every commit should be prefixed with fix: ... or feat: or similar.
> 
> without any fix or feat, no new release gets triggered.

Sorry, my fault...

**Pull request merged**
