### PR TITLE
fix(deps): upgrade nexus-plugin-prisma to 0.18.2

### PR DESCRIPTION
**Pull request by izziaraffaele**
It should solve https://github.com/panter/ra-data-prisma/issues/38

### CODE REVIEW

**Comment by macrozone** [comment]
nice @izziaraffaele !

I think that might be a breaking change, right? Can you therefore add a line

`BREAKING CHANGE: xxxxx` to the commit? (see https://github.com/semantic-release/semantic-release#how-does-it-work)

that will bump the major version.

**Comment by izziaraffaele** [comment]
> I think that might be a breaking change, right? 

I wasn't sure at the start to include the breaking changes line or not as if you're using both the backend and the dataprovider package nothing really changes but, thinking more about it I agree with you. I'll add a new commit

**Comment by macrozone** [comment]
> > I think that might be a breaking change, right?
> 
> I wasn't sure at the start to include the breaking changes line or not as if you're using both the backend and the dataprovider package nothing really changes but, thinking more about it I agree with you. I'll add a new commit

that was also my thought, but i know from some of our own project that the generated crud api is used outside of react-admin, so it could be a breaking change.

This is also a reason why i introduced a prefix option that prefixes all queries or mutations created by this project, e.g. you can prefix everything with "admin" to make it more obvious which resolvers are for the admin

**Comment by izziaraffaele** [comment]
Hey @macrozone, when do you think this could be merged?

**Comment by macrozone** [comment]
ah sure, sorry

**Pull request merged**
